### ISSUE TITLE
Face2dog

### ISSUE THREAD

**Issue by hh23333** [siyuhuang/Latent-Space-Anchoring#1]
Hello, I am very interested in your paper and your code. I wonder how you can transform a human face into a dog face, as shown in Figure 6 of your paper. Could you please provide the corresponding pre-trained model? Thank you very much!

**Comment by siyuhuang** [comment]
Hi @hh23333 , as stated in our paper's Section 6 LIMITATION AND ETHICAL STATEMENT: `As shown by the experimental results, our method can be used in human and animal face translation, which is considered a potential ethical issue. To prevent the abusive usage of the proposed method, the codes and model checkpoints of the human/animation translation are not released to the public.`

We will not release the human-animal face translation codes publicly. Sorry for that and thank you for your understanding.
